config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources  :users
  resources  :meals
  resources :servings do
    resources :orders
  end

  resources :comments, only: [:create, :destroy]

  get "/inbox", to: "orders#inbox"
  get "/outbox", to: "orders#outbox"
  get "/map", to: "statics#map"
  root "statics#home"

  resources :orders, only: [] do 
    member do
      get "accept"
      get "reject"
      get "cancel"
    end
 end


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable
  
  def create
    @comment = @commentable.comments.build(comments_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: "Thanks for commenting." }
      else
        format.html { redirect_to @commentable, notice: "Comment wasn't successfully created." }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to @commentable, notice: "Your comment was successfully destroyed."}
      format.json { head :no_content }
    end
  end
  
  protected
    def set_commentable
      @commentable = params[:commentable_type].camelize.constantize.find(params[:commentable_id])
    end

    def comments_params
      params.require(:comment).permit(:title, :comment)
    end
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="medium-6 columns">
    <div class="callout-card">
      <div class="card-label">
        <div class="label-text">
          Yo!
        </div>
      </div>
      <div class="callout-card-content">
        <h3 class="lead"> <%= comment.title %></h3>
        <p><%= comment.comment %></p>
        Author: <%= comment.user.try(:name) %>  <br> 
        <%= link_to 'Delete Comment', comment_path(comment, commentable_type: commentable.class.to_s.underscore, commentable_id: commentable.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
  </div>

app/views/comments/_form.html.erb
<div class="medium-4 columns" data-equalizer-watch>
<%= form_for(:comment, url: comments_path(commentable_type: commentable.class.to_s.underscore, commentable_id: commentable.id)) do |f| %>

  <%= f.text_area :title, placeholder: "Add a title" %>
  <%= f.text_area :comment, placeholder: "Write a Comment" %>
  <%= f.submit class: "button succes" %>

<% end %>
</div>