config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources  :users
  resources  :meals
  resources :servings do
    resources :orders
  end

  resources :comments, only: [:create, :destroy]

  get "/inbox", to: "orders#inbox"
  get "/outbox", to: "orders#outbox"
  get "/map", to: "statics#map"
  root "statics#home"

  resources :orders, only: [] do 
    member do
      get "accept"
      get "reject"
      get "cancel"
    end
 end


end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :serving
  



  before_validation :add_default_status

  def accept!
      self.status = "accepted"
      self.save
  end

  def reject!
      self.status = "rejected"
      self.save
  end

  def cancel!
      self.destroy
  end


  private
      def add_default_status
          self.status = "pending" if self.status.nil?
      end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :search_params 
before_action :authenticate_user!
before_action :set_order, only: [:accept, :reject, :cancel]

  def new
    @serving = Serving.find(params[:serving_id])
    @order = Order.new
  end

  def create
    @serving = Serving.find(params[:serving_id])
    @order = @serving.orders.new(order_params)
    @order.sender_id = current_user.id
    @order.receiver_id = @serving.user_id

    if @order.save
      flash[:success] = "Your order was made sucessfully"
      redirect_to servings_path
    else
      flash[:danger] = "Not sent"
      redirect_to servings_path
    end
  end

  def inbox
  end

  def inbox
  end

  def accept
    @order.accept!
    flash[:sucess] = "You accepted the order"
    redirect_to :back
  end

  def reject
    @order.reject!
    flash[:danger] = "You rejected the order"
    redirect_to :back
  end

  def cancel
    @order.cancel!
    flash[:info] = "You cancel the order"
    redirect_to :back
  end


  private 

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:details, :receiver_id)
  end
  
  def search_params
    @q = Serving.search(params[:q])
    @servings = @q.result(distinct: true)
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<div class="row">
  <div class="medium-8 columns">
    <div class="callout-card">
      <div class="card-label">
        <div class="label-text">
          Order!
        </div>
      </div>
      <div class="callout-card-content">
        <h3 class="lead"> <%= order.serving.meal.title %> : <i><%= order.status %></i></h3>
        <% if current_page?(action: "outbox") %>
        <h4 class="lead">Cook : <%= order.serving.meal.user.name %></h4>
        <% end %>

        <p><%= order.details %></p>
      </div>
      <div class="actions pull-xs-right">
        <% if current_page?(action: "outbox") %>
          <%= link_to "Cancel", cancel_order_path(order), class: "button disabled" %>
        <% else %>
          <%= link_to "Reject", reject_order_path(order), class: "button alert" %>
          <%= link_to "Accept", accept_order_path(order), class: "button success" %>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/orders/inbox.html.erb
<div class="row">
  <h1>Requested Meal</h1>
  <%= render current_user.orders_as_receiver %>
</div>

app/views/orders/new.html.erb
<div class ="row spacer" data-equalizer>
<h1>New Order</h1>
  <div class="medium-4 columns" data-equalizer-watch>
    <div class="card">
      <div class="image" style="height: 200px">
        <img src="<%= @serving.meal.graffiti_image %>">
        <span class="title">Cook : <%= @serving.meal.user.name %></span>
      </div>
      <div class="Main-content">
        <h5><%= link_to "#{@serving.meal.title}", serving_path(@serving.id) %></h5>
        <hr>
      </div>
      <div class="content"> <%= @serving.meal.description %>
        <hr>
      </div>
      <div class="content">
        <ul class="small-block-grid-2">
          <li><h5>Day:</h5><b><%= @serving.day %></b></li>
          <li><h5>Location:</h5><b><%= @serving.location %></b></li>
        </ul>
        <ul class="small-block-grid-2">
          <li><h5>Price:</h5><b>£<%= @serving.price %></b></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="medium-8 columns" data-equalizer-watch>
<%= form_for [@serving, @order] do |f| %>
  <% if @order.errors.any? %>
    <% for message in @order.errors.full_messages %>
      <div class="alert-box alert round" role="alert">
        <%= message %>
      </div>
    <% end %>
  <% end %>


    <%= f.label :details %>
    <%= f.text_area :details, class: "form-control" %>

  <%= f.submit class: "button success" %>
<% end %>
</div>
</div>

app/views/orders/outbox.html.erb
<div class="row">
<h1>Ordered Meal</h1>
<%= render current_user.orders_as_sender %>
</div>