config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources  :users
  resources  :meals
  resources :servings do
    resources :orders
  end

  resources :comments, only: [:create, :destroy]

  get "/inbox", to: "orders#inbox"
  get "/outbox", to: "orders#outbox"
  get "/map", to: "statics#map"
  root "statics#home"

  resources :orders, only: [] do 
    member do
      get "accept"
      get "reject"
      get "cancel"
    end
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
   def after_sign_in_path_for(resource)
     root_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Contact Page</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Press Realeased</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Meal Box", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to "All Food !", servings_path%></li>
        <li class="divider"></li>
        <li><%= link_to "All Cooks", users_path%></li>
        <li class="divider"></li>
        <li><%= link_to "On a Map", map_path%></li>    
        <li class="divider"></li>
        <% if current_user %>
        <li class="has-dropdown">
          <%= link_to "My Profile", user_path(current_user)  %>
          <ul class="dropdown">
            <li><%= link_to 'Add a meal', new_meal_path %></li>
            <li><%= link_to "Requested Servings", inbox_path, class: "nav-link" %></li>
            <li><%= link_to "Ordered Meals", outbox_path, class: "nav-link" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li class="has-dropdown">
          <a href="#">Join</a>
          <ul class="dropdown">
           <li><%= link_to "Log In", new_user_session_path %></li>
           <li><%= link_to "Register", new_user_registration_path %></li>
         </ul>
       </li>
       <% end %>
     </ul>
   </section>
 </nav>
</header>